language: php

dist: xenial

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION="2.x-dev" DB=MYSQL

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update cwp/starter-theme 2.x-dev sminnee/phpunit-mock-objects ^3.4.7
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit --testsuite cwp-recipe-search
